### ISSUE TITLE
Various visual effects no longer working

### ISSUE THREAD

**Issue by C-Tak** [Lyall/SoulHackers2Fix#3]
The fix works great, but I’ve noticed multiple visual/special effects no longer seem to work. This includes spell effects, muzzle flash from guns and the light coming from warp points. 

Anyway to fix this in the config?

**Comment by Lyall** [comment]
Is this with the chromatic aberration toggle on? I can't seem to replicate the issue you described on my end. What platform are you seeing the issue on? Steam Deck, Linux, or Windows?

**Comment by C-Tak** [comment]
Yeah it’s super strange. This is on Steam Deck, running Proton GE-30. DisableChromaticAberration set to False.

**Comment by Lyall** [comment]
Okay so based on what other people are describing on [ProtonDB](https://www.protondb.com/app/1777620), it looks like it's an issue with Proton. I don't think there's anything in the fix causing the issue and there's nothing I can really do about it I'm afraid. Will probably just have to wait for a Proton/Proton-GE update or if anyone finds a config that fixes the issues.

**Comment by C-Tak** [comment]
That’s okay, I’ll continue messing around with proton if that’s the case. Again, great work on the fix!

**Comment by Lyall** [comment]
So I've tried the game without the fix using Proton-GE-30 and Proton-GE-31 and certain effects definitely do not render. One of the most obvious examples is the sword slash attack you can do with Ringo. It's supposed to have a green trail effect but it does not render correctly with Proton. So it's 100% on Proton and not the fix therefore I'll close the issue for now. Fingers crossed this will get fixed as otherwise the game actually runs really well on the Steam Deck.
